### ISSUE TITLE
Bios setup

### ISSUE THREAD

**Issue by MartinGambit** [Edwardwich/hp-DA1023nia-macOS#6]
Hello, I would love to try your set up. I have almost exactly the same laptop but I am having issues accessing advanced bios settings. I would really appreciate your help a lot.

My laptop: Hp 15 da-1xxx, i5-8265U, iGPU UHD620, 16Gb ram, 
Bios version - f.23, type- Insyde

I have been trying to set up hackintosh a long week but it seems that my HP version is a bit tricky..

**Comment by Edwardwich** [comment]
> Hello, I would love to try your set up. I have almost exactly the same laptop but I am having issues accessing advanced bios settings. I would really appreciate your help a lot.
> 
> My laptop: Hp 15 da-1xxx, i5-8265U, iGPU UHD620, 16Gb ram, 
> Bios version - f.23, type- Insyde
> 
> 
> I have been trying to set up hackintosh a long week but it seems that my HP version is a bit tricky..

Hi send screen shot of bios information tab

**Comment by MartinGambit** [comment]
I have slightly adjusted the file. I do see the logo with loading even tho I added -v into boot args which does not make sense to me. But in debug message I get this:
[opencore-2023-12-19-151826.txt](https://github.com/Edwardwich/hp-DA1023nia-macOS/files/13716762/opencore-2023-12-19-151826.txt)
This is my config.plist 
I have been able to manually disable CFG Lock.

**Comment by Edwardwich** [comment]
send telegram PM @Aligh2966
